import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  lessons: defineTable({
    date: v.string(),
    slug: v.optional(v.string()),
    order: v.optional(v.number()),
    title: v.string(),
    source: v.optional(v.string()),
    sourceMarkdownFile: v.optional(v.string()),
    jsonPath: v.optional(v.string()),
    jsonUrl: v.optional(v.string()),
    contentHash: v.optional(v.string()),
    notes: v.optional(v.string()),
    priority: v.optional(v.number()),
    lastReviewedAt: v.optional(v.number()),
    reviewScore: v.optional(v.number()),
    refreshCount: v.optional(v.number()),
    tags: v.optional(v.array(v.string())),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_date", ["date"]).index("by_slug", ["slug"]),

  sentences: defineTable({
    lessonId: v.id("lessons"),
    order: v.number(),
    original: v.string(),
    corrected: v.optional(v.string()),
    explanation: v.optional(v.string()),
    naturalAlternative: v.optional(v.string()),
    status: v.union(v.literal("correct"), v.literal("minor"), v.literal("fix"), v.literal("unreviewed")),
    tags: v.array(v.string()),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_lesson_order", ["lessonId", "order"]),

  reviewCards: defineTable({
    sourceSentenceId: v.optional(v.id("sentences")),
    lessonId: v.optional(v.id("lessons")),
    lessonSlug: v.optional(v.string()),
    prompt: v.string(),
    answer: v.string(),
    cardType: v.union(v.literal("fix_sentence"), v.literal("choose"), v.literal("fill_blank"), v.literal("translate"), v.literal("note")),
    dueDate: v.optional(v.string()),
    difficulty: v.optional(v.union(v.literal("again"), v.literal("hard"), v.literal("good"), v.literal("easy"))),
    intervalDays: v.optional(v.number()),
    priority: v.optional(v.number()),
    lastReviewedAt: v.optional(v.number()),
    reviewScore: v.optional(v.number()),
    tags: v.array(v.string()),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_due_date", ["dueDate"]).index("by_lesson_slug", ["lessonSlug"]),
});
